config/routes.rb
Gostore::Application.routes.draw do
  resources :orders
  resources :carts
  resources :line_items
  resources :categories

  root :to=> 'store#index', :via => :get
  root :to=> 'store#index', :via => :post
  match 'store/:id' => 'store#show', :as => 'store_product', :via => :get
  match '/about_us' => 'about_pages#show', :as => 'about_us', :via => :get
  match '/contact_us' => 'contact_pages#show', :as => 'contact_us', :via => :get
  match '/category/:category' => 'store#index', :as => 'store_category', :via => :get
  match '/new_order' => 'orders#new', :as => 'new_order', :via => :get
  match '/show_invoice' => 'orders#show', :as => 'show_order', :via => :get
  match 'search' => 'store#search', :as=>'search', :via => :get
  match '/search_results' => 'store#search_results', :as => 'search_results', :via => :post
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :description, :name
  has_many :products
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :category_id, :description, :image_url, :mark_as_new, :mark_as_sale, :material, :price, :quantity, :sale_price, :title
  belongs_to :category
  validates :description, :title, :price, :presence => true
  validates :price, :numericality => true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)$}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }

  has_many :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  private
   def ensure_not_referenced_by_any_line_item
     if line_items.empty?
       return true
     else
        errors.add(:base, 'Line Items present')
        return false
     end
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  private
    def current_cart
      Cart.find(session[:cart_id])
    rescue ActiveRecord::RecordNotFound
      cart = Cart.create
       session[:cart_id] = cart.id
       cart
     end
end

app/controllers/categories_controllerold.rb
class CategoriesController < InheritedResources::Base
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @cart = current_cart
    if params[:category].present?
      if Category.find_by_name(params[:category]).present?
         @products = Category.find_by_name(params[:category])
      else  
         @products = Product.all
      end     
    else
      @products = Product.all
    end
  end
  
  def show
    @cart = current_cart
    @categories = Category.all
    @product = Product.find(params[:id])
  end
  
  def search
    @cart = current_cart
    # No code is required here.
  end # Automatically loads app/views/store/search.html.erb
  
  def search_results
    @cart = current_cart
    if params[:category].present?
      @products = Product.where('category_id' => params[:category])
    end
    if params[:keywords].present?# Here we will be using the Product model to actually search.
      @products = Product.where("title LIKE ? OR description LIKE? ", "%#{params[:keywords]}%", "%#{params[:keywords]}%")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/categoriesold/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categoriesold/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categoriesold/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categoriesold/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categoriesold/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.name %>
</p>

<p>
  <b>Description:</b>
  <%= @category.description %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gostore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">	
		<div class="page-header">
		  <h1>Go Store <small>Get Anything you need about GO</small></h1>
		</div>
		<nav class="navbar navbar-default" role="navigation">
	    <ul class="nav navbar-nav">
	      <li class="active"><%= link_to 'Home', root_path, :class => 'hello' %></li>
				<li><%= link_to "About Us", about_us_path %></li>
	      <li><%= link_to 'Go Game Sets', store_category_path(:category => 'Set') %></li>
	      <li><%= link_to 'Go Boards', store_category_path(:category => 'Board') %></li>
	      <li><%= link_to 'Go Stones', store_category_path(:category => 'Stone') %></li>
	      <li><%= link_to 'Go Bowls', store_category_path(:category => 'Bowl') %></li>
	      <li><%= link_to "Contanct Us", contact_us_path %></li>
	    </ul>
	  </nav>
	  <div class="row">
	  	<aside id="side" class="col-md-2">
		<%= render 'store/search' %>
		  <div id="cart">
        <%= render(@cart) %>
      </div>	  	
	  	</aside>
			<div class="col-md-10">
			<%= yield %>
			</div>
		</div>
	</div>

</body>
</html>

app/views/products/_product.html.erb
<div class="entry">
<div>
<%= image_tag(product.image_url, :class => 'img-responsive', :alt => 'Responsive_image', :width => '200') %>
<%= link_to product.title, store_product_path(product) %>
</div>
<div class="price_line">
<span class="price"><%= number_to_currency(product.price) %></span>
<%= button_to 'Add to Cart', line_items_path(product_id: product) %>
</div>
</div>

app/views/store/index.html.erb
<%= render @products %>

app/views/store/search_results.html.erb
<h2>Search Results</h2>

<% if @products.empty? %>
  <p>
    Sorry your search for '<%= params[:keywords] %>' returned no results.
  </p>
<% end %>

<%= render @products %>

app/views/store/show.html.erb
<%= render @product %>
<table border='1'>
	<tr>
		<td class="firstcolumn">Name</td>
		<td class="secondcolumn"><%= @product.title %></td>
	</tr>
	<tr>
		<td class="firstcolumn" valign="top">Details</td> 
		<td class="secondcolumn"><%= @product.description %></td>
	</tr>
	<tr>
		<td class="firstcolumn">Material</td>
		<td class="secondcolumn"><%= @product.material %></td>
	</tr>
	<tr>
		<td class="firstcolumn">Price</td>
		<td class="secondcolumn"><%= number_to_currency(@product.price) %></td>
	</tr>
	<% if @product.mark_as_sale.present? %>
		<tr>
			<td class="firstcolumn">On Sale</td>
			<td class="secondcolumn"><%= number_to_currency(@product.sale_price) %></td>
		</tr>
	<% end %>
	<% if @product.quantity > 0 %>
		<tr><td colspan='2'>In Stock</td></tr>
	<% else %>
		<tr><td colspan='2'>Out of Stock</td></tr>
	<% end %>
</ul>
</div>